### ISSUE TITLE
compress_model_size

### ISSUE THREAD

**Issue by 3DMM-ICME2023** [evcu/cv2016#1]
Thanks for your nice code and wonderful works! @evcu
Did you compress the cnn model size?

**Comment by evcu** [comment]
Hi liu, thanks for the msg. I didn't write the code to compress/serialize the pruned network. 

Now I am working on implementing prunning on pyTorch, I will release that soon.

**Comment by evcu** [comment]
first version is here: https://github.com/evcu/pytorchpruner
